### ISSUE TITLE
Revoked HMDB ID(s)

### ISSUE THREAD

**Issue by DeniseSl22** [bridgedb/tiwid#6]
Stumbled on this by chance @egonw :
![image](https://user-images.githubusercontent.com/26277832/124923724-0777a900-dffb-11eb-8c2a-36dc05fdb313.png)

**Comment by egonw** [comment]
Closed with https://github.com/bridgedb/tiwid/commit/fc6bddd686e85cb2e7db08e6cd6053895d3bd7b4
